name: Build Laravel App

on:
  push:
    branches:
        - main

jobs:
    setup:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Generate deployment timestamp
          id: timestamp
          run: echo "TIMESTAMP=$(date + %Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        
        - name: Cache Composer Dependencies
          uses: actions/cache@v3
          with:
            path: vendor
            key: ${{runner.os}}-composer-${{ hashFiles('composer.lock')}}
            restore-keys: |
              ${{ runner.os }}-composer-
           

    test:
        runs-on: ubuntu-latest
        needs: [setup]

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
                php-version: '8.3'
                extensions: mbstring, xml, bcmath, ctype, fileinfo, json, tokenizer, openssl, pdo, pdo_mysql
                coverage: pcov
                tools: composer:v2

          - name: Install dependencies
            run: |
              composer install --prefer-dist --no-progress

            
          - name: Prepare environment
            run: |
              mkdir -p database
              touch database/database.sqlite

              cp .env.example .env.testing

              echo "APP_ENV=testing" >> .env.testing
              echo "DB_CONNECTION=sqlite" >> .env.testing
              echo "DB_DATABASE=$(pwd)/database/database.sqlite" >> .env.testing

              mkdir -p storage/framework/{cache,sessions,views}
              chmod -R 777 storage bootstrap/cache
               
          - name: Generate key
            run: php artisan key:generate --env=testing

          - name: Run migrations
            run: php artisan migrate --env=testing --force     



          

